
sentiment:
    num_classes: 7
    classification_type: 'multiclass'
    multi_class: 'ovr' # one of ['ovr','ovo', 'no'] - for multiclass scoring. ovr means one-with-rest ,
                    # ovo - all possible pairwise combinations, no - don't use (for multilabel)
    average: 'weighted' # for metrics: micro, macro or weighted
    size: 'small'

    treshold: 0.5
    classes:
        no_emotion: 0
        anger: 1
        disgust: 2
        fear: 3
        happiness: 4
        sadness: 5
        surprise: 6

    path_to_weights: 'weights/sentiment'